[package]
name = "nogamepads-export"
authors = [ "CatilGrass" ]

workspace = "../../NoGamepads"
edition = "2024"

[dependencies]
nogamepads = { path = "../../NoGamepads" }
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.7.8"