#./
[release.root]
license = { raw = "./", target = "./", files = ["LICENSE-LGPL-2", "LICENSE-THIRD-PARTY"] }
powershell_complete = { raw = "./.cargo/resources/scripts/", target = "./bin/completeion", files = ["install_completion_powershell.ps1"] }

#./.cargo/shared/target/export/deps
[release.deps]
padc = { raw = "./", target = "./bin", files = ["padc.exe"] }

