# No Gamepads Export Configure
# This document details release file information for executing cargo export or cargo dev.

# Items defined in [release.root]
#   It will search starting from the project directory and copy to the specified location in the target directory.
[release.root]

# License files, third-party licenses
license = { raw = "./", target = "./", files = [
    "LICENSE-MIT"
] }

# Powershell auto-completion scripts
powershell_complete = { raw = "./.cargo/resources/scripts/", target = "./bin/completeion", files = [
    "install_completion_powershell.ps1"
] }

# Headers
headers = { raw = "./core/bindings/c_lang/headers/", target = "./lib", files = [
    "ngpd_player.h"
] }

# Items defined in [release.deps]
#   It will search starting from the build directory and copy to the specified location in the target directory.
[release.deps]

# Windows executables
win_exes = { raw = "./", target = "./bin", files = [
    "padc.exe", "pad.exe"
] }

# Windows dynamic link libraries
dlls = { raw = "./", target = "./lib", files = [
    "nogamepads_c.dll"
] }