# No Gamepads Export Configure
# This document details release file information for executing cargo export or cargo dev.

# Items defined in [release.root]
#   It will search starting from the project directory and copy to the specified location in the target directory.
[release.root]

# License files
license = { raw = "./", target = "./", files = [
    "LICENSE-MIT"
] }

# Powershell auto-completion scripts
powershell_complete = { raw = "./.cargo/resources/scripts/", target = "./bin/completeion", files = [
    "install_completion_powershell.ps1"
] }

# Headers
headers = { raw = "./core/bindings/lang/clang/headers/", target = "./lib", files = [
    "nogamepads_data.h",
] }

# Items defined in [release.deps]
#   It will search starting from the build directory and copy to the specified location in the target directory.
[release.deps]

# Windows executables
win_exes = { raw = "./", target = "./bin", files = [
    "padc.exe", "pad.exe"
] }

# Windows dynamic link libraries
dlls = { raw = "./", target = "./lib", files = [
    "nogamepads_c.dll",
    "nogamepads_c.dll.lib"
] }

[release.deploy_root]

# Headers
headers = { raw = "./core/bindings/lang/clang/headers/", target = "./core/bindings/lang/clang/binding_example/include/", files = [
    "nogamepads_data.h",
] }

[release.deploy_deps]

c_binding_example_win = { raw = "./", target = "./core/bindings/lang/clang/binding_example/libs/", files = [
    "nogamepads_c.dll",
    "nogamepads_c.dll.lib"
] }

csharp_binding_win = { raw = "./", target = "./core/bindings/lang/csharp/NoGamepads_CharpBindings/NoGamepads_Core/Native/", files = [
    "nogamepads_c.dll",
] }