[package]
name = "nogamepads-c-bindings"
edition = "2024"
version.workspace = true

[dependencies]
nogamepads-core = { path = "./../../../../core" }
libc = "0.2.172"

[lib]
name = "nogamepads_c"
crate-type = ["cdylib"]
