[build]
target-dir = "./.cargo/shared/target"

[env]
PROJECT_VERSION = { value = "0.1.0" }

TEST_PLAYER_ACCOUNT = { value = "Ame.Na.LISA" }
TEST_PLAYER_PASSWORD = { value = "amenalisa@@:P_QWQ" }

TEST_PLAYER_NICKNAME = { value = "ame_na_lisa" }