[alias]
dev = ["run", "--manifest-path", "./export/Cargo.toml", "--profile", "dev", "--bin", "export_project", "dev"]
export = ["run", "--manifest-path", "./export/Cargo.toml", "--profile", "release", "--release", "--bin", "export_project"]

padc = ["run", "--manifest-path", "./console/Cargo.toml", "--profile", "dev", "--quiet", "--bin", "padc"]

[build]
target-dir = "./.cargo/shared/target"

[env]

# Project Settings
PROJECT_VERSION = { value = "0.1.0" }

# Pad Console Cli
TEST_PLAYER_ACCOUNT = { value = "ame_na_lisa" }
TEST_PLAYER_PASSWORD = { value = "amenalisa@@:P_QWQ" }
TEST_PLAYER_NICKNAME = { value = "Ame.Na.LISA" }
